const House = [
  {id:1, name:'Ramon Alexander', district:8, party:'Democrat'},
  {id:2, name:'Vance Arthur Aloupis Jr.',district:115,party:'Republican'},
  {id:3, name:'Thad Altman',district:52,party:'Republican'},
  {id:4, name:'Robert Alexander Andrade',district:2,party:'Republican'},
  {id:5, name:'Bruce Antone',district:2,party:'Republican'},
  {id:6, name:'Loranne Ausley',district:9,party:'Democrat'},
  {id:7, name:'Bryan Avilla',district:111,party:'Republican'},
  {id:8, name:'Melony M. Bell',district:,party:''},
  {id:9, name:'Mike Beltran',district:,party:''},
  {id:10, name:'Halsey Beshears',district:,party:''},
  {id:11, name:'Robert Charles Brannan III',district:,party:''},
  {id:12, name:'Kamia L. Brown',district:,party:''},
  {id:13, name:'James Buchanan',district:,party:''},
  {id:14, name:'Daniel Wright Burgess Jr.',district:,party:''},
  {id:15, name:'Colleen Burton',district:,party:''},
  {id:16, name:'Dr. James Bush III',district:,party:''},
  {id:17, name:'Cord Byrd',district:,party:''},
  {id:18, name:'Michael A. Caruso',district:,party:''},
  {id:19, name:'Joseph A. Casello',district:,party:''},
  {id:20, name:'Charles Wesley Clemons Sr.',district:,party:''},
  {id:21, name:'John Cortes',district:,party:''},
  {id:22, name:'Travis W. Cummings',district:,party:''},
  {id:23, name:'Kimberly Daniels',district:,party:''},
  {id:24, name:'Tracie Davis',district:,party:''},
  {id:25, name:'Ben Diamond',district:,party:''},
  {id:26, name:'Nick DiCeglie',district:,party:''},
  {id:27, name:'Byron Donalds',district:,party:''},
  {id:28, name:'Brad Drake',district:,party:''},
  {id:29, name:'Fentrice Driskell',district:,party:''},
  {id:30, name:'Bobby B. DuBose',district:,party:''},
  {id:31, name:'Wyman Duggan',district:,party:''},
  {id:32, name:'Nicholas X. Duran',district:,party:''},
  {id:33, name:'Dane Eagle',district:,party:''},
  {id:34, name:'Anna V. Eskamani',district:,party:''},
  {id:35, name:'Javier E. Fernandez',district:,party:''},
  {id:36, name:'Juan Alfonso Fernandez-Barquin',district:,party:''},
  {id:37, name:'Elizabeth Anne Fetterhoff',district:,party:''},
  {id:38, name:'Randy Fine',district:,party:''},
  {id:39, name:'Jason Fischer',district:,party:''},
  {id:40, name:'Heather Fitzenhagen',district:,party:''},
  {id:41, name:'Joseph Geller',district:,party:''},
  {id:42, name:'Joy Goff-Marcil',district:,party:''},
  {id:43, name:'Margaret Good',district:,party:''},
  {id:44, name:'Michael Gottlieb',district:,party:''},
  {id:45, name:'Erin Grall',district:,party:''},
  {id:46, name:'James Grant',district:,party:''},
  {id:47, name:'Michael Grant',district:,party:''},
  {id:48, name:'Tommy Gregory',district:,party:''},
  {id:49, name:'Michael Grieco',district:,party:''},
  {id:50, name:'Brett Thomas Hage',district:,party:''},
  {id:51, name:'Dianne Hart',district:,party:''},
  {id:52, name:'Adam Roger Hattersley',district:,party:''},
  {id:53, name:'Walter Bryan Hill',district:,party:''},
  {id:54, name:'Delores D. Hogan Johnson',district:,party:''},
  {id:55, name:'Blaise Ingoglia',district:,party:''},
  {id:56, name:'Kristin Diane Jacobs',district:,party:''},
  {id:57, name:'Al Jacquet',district:,party:''},
  {id:58, name:'Evan Jenne',district:,party:''},
  {id:59, name:'Shervin D. Jones',district:,party:''},
  {id:60, name:'Dotie Joseph',district:,party:''},
  {id:61, name:'Sam H. Killebrew',district:,party:''},
  {id:62, name:'Mike La Rosa',district:,party:''},
  {id:63, name:'Chip LaMarca',district:,party:''},
  {id:64, name:'Chris Latvala',district:,party:''},
  {id:65, name:'Thomas J. Leek',district:,party:''},
  {id:66, name:'MaryLynn Magar',district:,party:''},
  {id:67, name:'Amber Mariano',district:,party:''},
  {id:68, name:'Ralph E. Massullo MD.',district:,party:''},
  {id:69, name:'Stan McClain',district:,party:''},
  {id:70, name:'Lawrence McClure',district:,party:''},
  {id:71, name:'Kionne L. McGhee',district:,party:''},
  {id:72, name:'Amy Mercado',district:,party:''},
  {id:73, name:'Jared Evan Moskowitz',district:,party:''},
  {id:74, name:'Wengay Newton',district:,party:''},
  {id:75, name:'Jose R. Oliva',district:,party:''},
  {id:76, name:'Anika Tene Omphroy',district:,party:''},
  {id:77, name:'Tobin Rogers Overdorf',district:,party:''},
  {id:78, name:'Bobby Payne',district:,party:''},
  {id:79, name:'Daniel Perez',district:,party:''},
  {id:80, name:'Cary Pigman',district:,party:''},
  {id:81, name:'Scott Plakon',district:,party:''},
  {id:82, name:'Rene Plasencia',district:,party:''},
  {id:83, name:'Cindy Polo',district:,party:''},
  {id:84, name:'Tina Scott Polsky',district:,party:''},
  {id:85, name:'Mel Ponder',district:,party:''},
  {id:86, name:'Sharon Pritchett',district:,party:''},
  {id:87, name:'Holly Raschein',district:,party:''},
  {id:88, name:'Paul Renner',district:,party:''},
  {id:89, name:'Spencer Roach',district:,party:''},
  {id:90, name:'William Cloud Robinson Jr.',district:,party:''},
  {id:91, name:'Ray Wesley Rodrigues',district:,party:''},
  {id:92, name:'Ana Maria Rodriguez',district:,party:''},
  {id:93, name:'Anthony Rodriguez',district:,party:''},
  {id:94, name:'Bob Rommel',district:,party:''},
  {id:95, name:'Rick Roth',district:,party:''},
  {id:96, name:'Anthony Sabatini',district:,party:''},
  {id:97, name:'David Santiago',district:,party:''},
  {id:98, name:'David Silvers',district:87,party:'Democrat'},
  {id:99, name:'Tyler I. Sirois',district:51,party:'Republican'},
  {id:100, name:'Emily Solsberg',district:91,party:'Democrat'},
  {id:101, name:'Carlos Guillermo Smith',district:49,party:'Democrat'},
  {id:102, name:'David Smith',district:28,party:'Republican'},
  {id:103, name:'Chris Sprowls',district:65,party:'Republican'},
  {id:104, name:'Richard Stark',district:104,party:'Democrat'},
  {id:105, name:'Cyndi Stevenson',district:17,party:'Republican'},
  {id:106, name:'Charlie Stone',district:22,party:'Republican'},
  {id:107, name:'Jennifer Mae Sullivan',district:31,party:'Republican'},
  {id:108, name:'Geraldine F. Thompson',district:44,party:'Democrat'},
  {id:109, name:'Jackie Toledo',district:60,party:'Republican'},
  {id:110, name:'Josie Tomkow',district:39,party:'Republican'},
  {id:111, name:'Jay Trumbull',district:6,party:'Republican'},
  {id:112, name:'Susan L. Valdes',district:62,party:'Democrat'},
  {id:113, name:'Barbara Watson',district:107,party:'Democrat'},
  {id:114, name:'Clovis Watson Jr.',district:20,party:'Democrat'},
  {id:115, name:'Jennifer Necole Webb',district:69,party:'Democrat'},
  {id:116, name:'Matt Willhite',district:86,party:'Democrat'},
  {id:117, name:'Patricia H. Williams',district:92,party:'Democrat'},
  {id:118, name:'Jayer Williamson',district:3,party:'Republican'},
  {id:119, name:'Clay Yarborough',district:12,party:'Republican'},
  {id:120, name:'Ardian Zika',district:37,party:'Republican'}
];

export default House;
