const House = [
  {id:1, name:'Ramon Alexander', district:8, party:'Democrat'},
  {id:2, name:'Vance Arthur Aloupis Jr.',district:115,party:'Republican'},
  {id:3, name:'Thad Altman',district:52,party:'Republican'},
  {id:4, name:'Robert Alexander Andrade',district:2,party:'Republican'},
  {id:5, name:'Bruce Antone',district:2,party:'Republican'},
  {id:6, name:'Loranne Ausley',district:9,party:'Democrat'},
  {id:7, name:'Bryan Avilla',district:111,party:'Republican'},
  {id:8, name:'Melony M. Bell',district:56,party:'Republican'},
  {id:9, name:'Mike Beltran',district:57,party:'Republican'},
  {id:10, name:'Halsey Beshears',district:7,party:'Republican'},
  {id:11, name:'Robert Charles Brannan III',district:10,party:'Republican'},
  {id:12, name:'Kamia L. Brown',district:45,party:'Democrat'},
  {id:13, name:'James Buchanan',district:74,party:'Republican'},
  {id:14, name:'Daniel Wright Burgess Jr.',district:38,party:'Republican'},
  {id:15, name:'Colleen Burton',district:40,party:'Republican'},
  {id:16, name:'Dr. James Bush III',district:109,party:'Democrat'},
  {id:17, name:'Cord Byrd',district:11,party:'Republican'},
  {id:18, name:'Michael A. Caruso',district:89,party:'Republican'},
  {id:19, name:'Joseph A. Casello',district:90,party:'Democrat'},
  {id:20, name:'Charles Wesley Clemons Sr.',district:21,party:'Republican'},
  {id:21, name:'John Cortes',district:43,party:'Democrat'},
  {id:22, name:'Travis W. Cummings',district:18,party:'Republican'},
  {id:23, name:'Kimberly Daniels',district:14,party:'Democrat'},
  {id:24, name:'Tracie Davis',district:13,party:'Democrat'},
  {id:25, name:'Ben Diamond',district:68,party:'Democrat'},
  {id:26, name:'Nick DiCeglie',district:66,party:'Republican'},
  {id:27, name:'Byron Donalds',district:80,party:'Republican'},
  {id:28, name:'Brad Drake',district:5,party:'Republican'},
  {id:29, name:'Fentrice Driskell',district:63,party:'Democrat'},
  {id:30, name:'Bobby B. DuBose',district:94,party:'Democrat'},
  {id:31, name:'Wyman Duggan',district:15,party:'Republican'},
  {id:32, name:'Nicholas X. Duran',district:112,party:'Democrat'},
  {id:33, name:'Dane Eagle',district:77,party:'Republican'},
  {id:34, name:'Anna V. Eskamani',district:47,party:'Democrat'},
  {id:35, name:'Javier E. Fernandez',district:114,party:'Democrat'},
  {id:36, name:'Juan Alfonso Fernandez-Barquin',district:119,party:'Republican'},
  {id:37, name:'Elizabeth Anne Fetterhoff',district:26,party:'Republican'},
  {id:38, name:'Randy Fine',district:53,party:'Republican'},
  {id:39, name:'Jason Fischer',district:16,party:'Republican'},
  {id:40, name:'Heather Fitzenhagen',district:78,party:'Republican'},
  {id:41, name:'Joseph Geller',district:100,party:'Democrat'},
  {id:42, name:'Joy Goff-Marcil',district:30,party:'Democrat'},
  {id:43, name:'Margaret Good',district:72,party:'Democrat'},
  {id:44, name:'Michael Gottlieb',district:98,party:'Democrat'},
  {id:45, name:'Erin Grall',district:54,party:'Republican'},
  {id:46, name:'James Grant',district:64,party:'Republican'},
  {id:47, name:'Michael Grant',district:75,party:'Republican'},
  {id:48, name:'Tommy Gregory',district:73,party:'Republican'},
  {id:49, name:'Michael Grieco',district:113,party:'Democrat'},
  {id:50, name:'Brett Thomas Hage',district:33,party:'Republican'},
  {id:51, name:'Dianne Hart',district:61,party:'Republican'},
  {id:52, name:'Adam Roger Hattersley',district:59,party:'Democrat'},
  {id:53, name:'Walter Bryan Hill',district:1,party:'Republican'},
  {id:54, name:'Delores D. Hogan Johnson',district:84,party:'Democrat'},
  {id:55, name:'Blaise Ingoglia',district:35,party:'Republican'},
  {id:56, name:'Kristin Diane Jacobs',district:96,party:'Democrat'},
  {id:57, name:'Al Jacquet',district:88,party:'Democrat'},
  {id:58, name:'Evan Jenne',district:99,party:'Democrat'},
  {id:59, name:'Shervin D. Jones',district:101,party:'Democrat'},
  {id:60, name:'Dotie Joseph',district:108,party:'Democrat'},
  {id:61, name:'Sam H. Killebrew',district:41,party:'Republican'},
  {id:62, name:'Mike La Rosa',district:42,party:'Republican'},
  {id:63, name:'Chip LaMarca',district:93,party:'Republican'},
  {id:64, name:'Chris Latvala',district:67,party:'Republican'},
  {id:65, name:'Thomas J. Leek',district:25,party:'Republican'},
  {id:66, name:'MaryLynn Magar',district:82,party:'Republican'},
  {id:67, name:'Amber Mariano',district:36,party:'Republican'},
  {id:68, name:'Ralph E. Massullo MD.',district:34,party:'Republican'},
  {id:69, name:'Stan McClain',district:23,party:'Republican'},
  {id:70, name:'Lawrence McClure',district:58,party:'Republican'},
  {id:71, name:'Kionne L. McGhee',district:117,party:'Democrat'},
  {id:72, name:'Amy Mercado',district:48,party:'Democrat'},
  {id:73, name:'Jared Evan Moskowitz',district:97,party:'Democrat'},
  {id:74, name:'Wengay Newton',district:70,party:'Democrat'},
  {id:75, name:'Jose R. Oliva',district:110,party:'Republican'},
  {id:76, name:'Anika Tene Omphroy',district:95,party:'Democrat'},
  {id:77, name:'Tobin Rogers Overdorf',district:83,party:'Republican'},
  {id:78, name:'Bobby Payne',district:19,party:'Republican'},
  {id:79, name:'Daniel Perez',district:116,party:'Republican'},
  {id:80, name:'Cary Pigman',district:55,party:'Republican'},
  {id:81, name:'Scott Plakon',district:29,party:'Republican'},
  {id:82, name:'Rene Plasencia',district:50,party:'Republican'},
  {id:83, name:'Cindy Polo',district:103,party:'Democrat'},
  {id:84, name:'Tina Scott Polsky',district:81,party:'Democrat'},
  {id:85, name:'Mel Ponder',district:4,party:'Republican'},
  {id:86, name:'Sharon Pritchett',district:102,party:'Democrat'},
  {id:87, name:'Holly Raschein',district:120,party:'Republican'},
  {id:88, name:'Paul Renner',district:24,party:'Republican'},
  {id:89, name:'Spencer Roach',district:79,party:'Republican'},
  {id:90, name:'William Cloud Robinson Jr.',district:71,party:'Republican'},
  {id:91, name:'Ray Wesley Rodrigues',district:76,party:'Republican'},
  {id:92, name:'Ana Maria Rodriguez',district:105,party:'Republican'},
  {id:93, name:'Anthony Rodriguez',district:118,party:'Republican'},
  {id:94, name:'Bob Rommel',district:106,party:'Republican'},
  {id:95, name:'Rick Roth',district:85,party:'Republican'},
  {id:96, name:'Anthony Sabatini',district:32,party:'Republican'},
  {id:97, name:'David Santiago',district:27,party:'Republican'},
  {id:98, name:'David Silvers',district:87,party:'Democrat'},
  {id:99, name:'Tyler I. Sirois',district:51,party:'Republican'},
  {id:100, name:'Emily Solsberg',district:91,party:'Democrat'},
  {id:101, name:'Carlos Guillermo Smith',district:49,party:'Democrat'},
  {id:102, name:'David Smith',district:28,party:'Republican'},
  {id:103, name:'Chris Sprowls',district:65,party:'Republican'},
  {id:104, name:'Richard Stark',district:104,party:'Democrat'},
  {id:105, name:'Cyndi Stevenson',district:17,party:'Republican'},
  {id:106, name:'Charlie Stone',district:22,party:'Republican'},
  {id:107, name:'Jennifer Mae Sullivan',district:31,party:'Republican'},
  {id:108, name:'Geraldine F. Thompson',district:44,party:'Democrat'},
  {id:109, name:'Jackie Toledo',district:60,party:'Republican'},
  {id:110, name:'Josie Tomkow',district:39,party:'Republican'},
  {id:111, name:'Jay Trumbull',district:6,party:'Republican'},
  {id:112, name:'Susan L. Valdes',district:62,party:'Democrat'},
  {id:113, name:'Barbara Watson',district:107,party:'Democrat'},
  {id:114, name:'Clovis Watson Jr.',district:20,party:'Democrat'},
  {id:115, name:'Jennifer Necole Webb',district:69,party:'Democrat'},
  {id:116, name:'Matt Willhite',district:86,party:'Democrat'},
  {id:117, name:'Patricia H. Williams',district:92,party:'Democrat'},
  {id:118, name:'Jayer Williamson',district:3,party:'Republican'},
  {id:119, name:'Clay Yarborough',district:12,party:'Republican'},
  {id:120, name:'Ardian Zika',district:37,party:'Republican'}
];

export default House;
