const Senators = [
  {id:1,name:'Ben Albritton', district:26,party:'Republican'},
  {id:2,name:'Dennis Baxley',district:12,party:'Republican'},
  {id:3,name:'Aaron Bean',district:4,party:'Republican'},
  {id:4,name:'Lizbeth Benacquisto',district:27,party:'Republican'},
  {id:5,name:'Lori Berman',district:31,party:'Democrat'},
  {id:6,name:'Lauren Book',district:32,party:'Democrat'},
  {id:7,name:'Randolph Bracy',district:11,party:'Democrat'},
  {id:8,name:'Rob Bradley',district:5,party:'Republican'},
  {id:9,name:'Jeff Brandes',district:24,party:'Republican'},
  {id:10,name:'Oscar Braynon II',district:35,party:'Democrat'},
  {id:11,name:'Doug Brozson',district:1,party:'Republican'},
  {id:12,name:'Janet Cruz',district:18,party:'Democrat'},
  {id:13,name:'Manny Diza Jr.',district:36,party:'Republican'},
  {id:14,name:'Gary M. Farmer Jr.',district:34,party:'Democrat'},
  {id:15,name:'Anitere Flores',district:39,party:'Republican'},
  {id:16,name:'George B. Gainer',district:2,party:'Republican'},
  {id:17,name:'Bill Galvano',district:21,party:'Republican'},
  {id:18,name:'Audrey Gibson',district:6,party:'Democrat'},
  {id:19,name:'Joe Gruters',district:23,party:'Republican'},
  {id:20,name:'Gayle Harrell',district:25,party:'Republican'},
  {id:21,name:'Ed Hooper',district:16,party:'Republican'},
  {id:22,name:'Travis Hutson',district:7,party:'Republican'},
  {id:23,name:'Tom Lee',district:20,party:'Republican'},
  {id:24,name:'Debbie Mayfield',district:17,party:'Republican'},
  {id:25,name:'Bill Montford',district:3,party:'Democrat'},
  {id:26,name:'Kathleen Passidomo',district:28,party:'Republican'},
  {id:27,name:'Keith Perry',district:8,party:'Republican'},
  {id:28,name:'Jason W.B. Pizzo',district:38,party:'Democrat'},
  {id:29,name:'Bobby Powell',district:30,party:'Democrat'},
  {id:30,name:'Kevin J. Rader',district:29,party:'Democrat'},
  {id:31,name:'Jose Javier Rodriguez',district:37,party:'Democrat'},
  {id:32,name:'Darryl Ervin Rouson',district:19,party:'Democrat'},
  {id:33,name:'David Simmons',district:9,party:'Republican'},
  {id:34,name:'Wilton Simpson',district:10,party:'Republican'},
  {id:35,name:'Kelli Stargel',district:22,party:'Republican'},
  {id:36,name:'Linda Stewart',district:13,party:'Democrat'},
  {id:37,name:'Annette Taddeo',district:40,party:'Democrat'},
  {id:38,name:'Perry E. Thurston Jr.',district:33,party:'Democrat'},
  {id:39,name:'Victor M. Torres Jr.',district:15,party:'Democrat'},
  {id:2,name:'Tom A. Wright',district:14,party:'Republican'}
];

export default Senators;
